### ISSUE TITLE
Clean up error message when Puzzle title is too long

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/cardboard#741] opened 2024-01-08 20:32 UTC
Right now, users might see this:

![image](https://github.com/cardinalitypuzzles/cardboard/assets/6751517/98a00a4f-072f-4b56-95f9-922c67e43ed0)

We should probably at least extract the error and avoid printing raw JSON.

**Comment by rgossiaux** [comment] 2024-01-09 02:31
Duplicate of #294 

We should certainly get around to fixing this at some point though

**Closed by rgossiaux** 2024-01-09 02:31 UTC
