### ISSUE TITLE
Add ability to sort by columns

### ISSUE THREAD

**Issue by rawxfish** [cardinalitypuzzles/cardboard#603] opened 2022-01-29 01:48 UTC
Such as answer and puzzle title, although unclear how this would interact with the meta-based tree sorting structure. Maybe sorting within each meta branch is best, since sorting by "Created" would return to the default sorting.

**Comment by rgossiaux** [comment] 2023-12-22 09:01
Duplicate of #436

**Closed by rgossiaux** 2023-12-22 09:01 UTC
Labels: enhancement, UI/UX
